module.exports = {
  out: './docs/',
  platform: 'github',
  theme: 'markdown',
  module: 'es2015',
  includes: './packages/**',
  exclude: ['**/__tests__/**/*', '**/*.types.ts'],
  mode: 'file',
  excludeExternals: true,
  excludeNotExported: true,
  excludePrivate: true,
  excludeProtected: true,
  target: 'ES6',
  tsconfig: './tsconfig.json',
  ignoreCompilerErrors: true,
};
